# processing/element_id_lookup_module.py
"""
element_id_lookup_module.py - Element ID lookup from offline table

Looks up LEGO element IDs given a (design_id, bricklink_color_id) pair using
the element_id_lookup.csv table generated by tools/database_update_tool.

RESPONSIBILITIES:
- Load element_id_lookup.csv into memory at startup
- Provide fast (design_id, color_id) → element_id lookup
- Return all element IDs for a pair (for bag-sorting doppelgänger matching)
- Degrade gracefully when the lookup table is absent

DOES NOT:
- Download or generate the lookup table (that's database_update_tool)
- Translate color IDs between systems (table already uses BrickLink IDs)
- Make business logic decisions about variant matching

LOOKUP TABLE:
The table is generated by tools/database_update_tool and contains entries
with columns: element_id, part_num, bricklink_color_id.
Mold-variant (M) and Alternate (A) expansions are pre-baked into the table,
so a single (part_num, bricklink_color_id) key may return multiple element IDs
representing different physical generations of the same piece.
Printed parts (P) are kept separate and are not merged into the canonical part.
"""

import csv
import logging
import threading
from typing import Optional, Dict, List, Tuple

from processing.processing_data_models import ElementLookupResult
from enhanced_config_manager import EnhancedConfigManager, ModuleConfig

logger = logging.getLogger(__name__)

# Type alias for the in-memory lookup index
_LookupKey = Tuple[str, str]   # (part_num, bricklink_color_id)
_LookupIndex = Dict[_LookupKey, List[str]]  # key → [element_id, ...]


class ElementIDLookup:
    """
    Offline element ID lookup using element_id_lookup.csv.

    Loads the full table into a dict at startup for O(1) lookups at runtime.
    Thread-safe via a read lock (writes only happen at init/reload).
    """

    def __init__(self, config_manager: EnhancedConfigManager):
        module_config = config_manager.get_module_config(ModuleConfig.PIECE_IDENTIFIER.value)
        self._lookup_path = module_config.get("element_id_lookup_path", "element_id_lookup.csv")
        self._lock = threading.Lock()
        self._index: _LookupIndex = {}
        self._loaded = False
        self._load()

    # =========================================================================
    # PUBLIC INTERFACE
    # =========================================================================

    def get_element_lookup(self, design_id: str, color_id: str) -> ElementLookupResult:
        """
        Look up all element IDs for a (design_id, bricklink_color_id) pair.

        Args:
            design_id:  Piece design ID as returned by Brickognize (e.g. "3001")
            color_id:   BrickLink color ID as returned by Brickognize (e.g. "5")

        Returns:
            ElementLookupResult.  found_in_lookup=False when the pair is absent.
        """
        if not self._loaded:
            return ElementLookupResult(element_id=None, all_element_ids=[], found_in_lookup=False)

        key = (design_id.strip(), str(color_id).strip())
        with self._lock:
            ids = self._index.get(key, [])

        if not ids:
            logger.debug(f"Element ID not found: design_id={design_id}, color_id={color_id}")
            return ElementLookupResult(element_id=None, all_element_ids=[], found_in_lookup=False)

        return ElementLookupResult(
            element_id=ids[0],
            all_element_ids=list(ids),
            found_in_lookup=True,
        )

    def get_element_id(self, design_id: str, color_id: str) -> Optional[str]:
        """
        Convenience method — returns only the primary element ID or None.

        For bag-sorting where all variants are needed, use get_element_lookup().
        """
        return self.get_element_lookup(design_id, color_id).element_id

    def is_loaded(self) -> bool:
        """True if the lookup table was successfully loaded."""
        return self._loaded

    def row_count(self) -> int:
        """Number of unique (part_num, color_id) keys in the loaded table."""
        with self._lock:
            return len(self._index)

    # =========================================================================
    # PRIVATE: LOADING
    # =========================================================================

    def _load(self) -> None:
        """Load element_id_lookup.csv into the in-memory index."""
        import os
        if not os.path.exists(self._lookup_path):
            logger.warning(
                f"Element ID lookup table not found at '{self._lookup_path}'. "
                f"Run tools/database_update_tool to generate it. "
                f"element_id will remain None for all pieces until then."
            )
            return

        index: _LookupIndex = {}
        rows_loaded = 0
        rows_skipped = 0

        try:
            with open(self._lookup_path, newline="", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    element_id = row.get("element_id", "").strip()
                    part_num = row.get("part_num", "").strip()
                    color_id = row.get("bricklink_color_id", "").strip()

                    if not (element_id and part_num and color_id):
                        rows_skipped += 1
                        continue

                    key = (part_num, color_id)
                    if key not in index:
                        index[key] = []
                    if element_id not in index[key]:  # avoid duplicates within key
                        index[key].append(element_id)
                    rows_loaded += 1

            with self._lock:
                self._index = index
            self._loaded = True

            logger.info(
                f"Element ID lookup loaded: {len(index)} unique (part, color) pairs "
                f"from {rows_loaded} rows ({rows_skipped} skipped)"
            )

        except Exception as e:
            logger.error(f"Failed to load element ID lookup table: {e}", exc_info=True)


# =============================================================================
# FACTORY FUNCTION
# =============================================================================

def create_element_id_lookup(config_manager: EnhancedConfigManager) -> ElementIDLookup:
    """
    Factory function to create an ElementIDLookup instance.

    Returns a fully initialised instance. If the lookup table file is absent,
    the instance is still returned — it will simply return found_in_lookup=False
    for every query until the table is generated and the application restarts.
    """
    return ElementIDLookup(config_manager)
